### PR TITLE
Add ignore_errors feature

### PR DESCRIPTION
**Pull request by salva**
Appenders sometimes die in order to report an unexpected issue found
while logging some message.

In some cases this is quite annoying for the programmer as exceptions
may pop up at any place where a logging sentence appears, and he would
have to handle it or just let the exception terminate the program.

Now, when the "ignore_errors" option is set, calls to appender objects
"log" method are wrapped inside eval blocks so that any error is
catched.

Note that appender errors happening at other Log::Log4perl stages (e.g.
initialization) are not caught.

### CODE REVIEW

**Comment by mschilli** [comment]
Thanks for your pull request! I'm a little concerned about ignoring errors and paying a runtime penalty for a the feature, though. In general, if an appender encounters an error (like a file appender running out of disk space), the error should raise up to the top. Offering an option to ignore it only seems to make things worse. If a program wants to have this feature, it is free to run everything within a big eval {}, but I don't think we should obfuscate this fact by providing a Log4perl feature for it. Did you have specific error conditions in mind, could they be handled more diligently within individual appenders?

**Comment by salva** [comment]
> if an appender encounters an error, the error should raise up to the top.

Well, it depends. That may be what you want in most cases, but there are still some ones where you may like the program to survive logging failures.

In my particular case I have a complex AnyEvent program that uses Log::Log4perl extensively and I don't want it to die just because the file system has become full. Instead my program would detect that situation and perform an ordered shutdown. But with logging methods throwing exceptions at any place that is impossible to do, I would have to wrap any logging call in an `eval` block which is unacceptable.

> I'm a little concerned about ignoring errors and paying a runtime penalty for the feature

When not enabled, the feature cost is just an extra, cheap, hash lookup inside an already quite long subroutine. It shouldn't be noticeable at all.

> could they be handled more diligently within individual appenders?

No, because I have no control over the appenders being used.

**Comment by mschilli** [comment]
What I'm worried about is the notion of "Got problems? Set ignore_errors=1 and keep going" which I can see being hastily enabled during a crisis and forgotten down the road, muting critical errors forever. 
I'd rather deal with errors when they occur. What's the use case you're worried about most, do you want to protect against a filled up file system or can you think of different scenarios you want to handle this way?

**Comment by salva** [comment]
> What's the use case you're worried about most?

We have an application that is deployed and configured by our customers in the way that best suits them and they are able to configure Log::Log4perl in any way. AFAIK, most of them use Log::Dispatch::FileRotate or/and Log::Dispatch::Syslog, but I have no control over the dispatchers they use, and the application should not die just because a random logging error.

So far, the reports we have identified as caused by the logger dying are all attributable to Log::Dispatch::FileRotate dying, after the file was rotated, when trying to create the new one because it lacked the permissions (happening in sections of code doing fork+setuid+exec) or because the file system had become full.

**Comment by mohawk2** [comment]
It doesn't seem there's much demand for this feature?

**Comment by mohawk2** [comment]
On reflection, the mentioned use-case (AnyEvent) is an example of async programming. Handling errors in that is a bit outside of scope for this module, whose behaviour is otherwise fine. I would suggest as a starting point for solving that class of problem to use a Promises-based interface, and append logging and error-catching `then`-handlers as appropriate.

I am therefore closing this, but am open to discussing / improving it with a view to reopening and merging if that were agreed as a useful way forwards.

**Pull request closed without merging**
