### PR TITLE
Do not warp 'message' after 'warp_message' function

### PR DESCRIPTION
**Pull request by KES777**

### CODE REVIEW

**Comment by mohawk2** [comment]
What benefit does this bring, given it's an incompatible change?

**Comment by KES777** [comment]
https://rt.cpan.org/Public/Bug/Display.html?id=107119

```
in config:
log4perl.appender.PsgiAPP.warp_message=  MasonHandler::log_filter

$ cat app.pl
...
$log->error( { zzz => 3 }, 'Hi' );

package MasonHandler;
use Data::Dump qw/ pp /;
sub log_filter {
    my @chunks =  @_;

    for my $msg ( @chunks ) {
        $msg =  pp $msg   if ref $msg;
    }

    return join $Log::Log4perl::JOIN_MSG_ARRAY_CHAR, @chunks;
};

I know about [this](http://search.cpan.org/~mschilli/Log-Log4perl-1.46/lib/Log/Log4perl/FAQ.pm#How_can_I_drill_down_on_references_before_logging_them?)

But it is too ugly to extra type with every call:
    $logger->debug( {filter => \&Data::Dumper::Dumper, value  => $ref} );
instead of 
    $logger->debug( $ref ); with implemented 'log_filter' as above


Please let 'warp_message' do its job and do not add extra [ ] So it would not break 'layout'

It seems some discussion here:
https://www.mail-archive.com/log4perl-devel@lists.sourceforge.net/msg00025.html
```

**Comment by KES777** [comment]
Precisely I do not remember. But from commit changes: returning array ref instead of list escapes from many copying. And this will save efficiency

**Comment by mohawk2** [comment]
Can you show benchmarks proving this benefit? Otherwise this is unacceptable as a breaking change.

**Comment by mohawk2** [comment]
I will close this for now. Please do comment with benchmark evidence if it does really improve things, and if so, it will be considered in that light.

**Pull request closed without merging**
