### PR TITLE
RT#120926

### PR DESCRIPTION
**Pull request by chorny**

### CODE REVIEW

**Comment by simon04** [comment]
This fixes #86.

**Comment by akiym** [comment]
@mschilli Ping ping. Some modules with dependency on Log::Log4perl failed CI on Windows. Could you merge and release to CPAN?

**Comment by Michael-Adams** [comment]
@mschilli : ***Ping Ping*** Chiming in with @akiym, Please merge and release!  This is also preventing any of *your* modules from installing on Win32 as they depend on Log\:\:Log4perl.  Thanks!

**Comment by jan-herout** [comment]
@mschilli: I second the notion. Pretty please, merge and release.

**Comment by mohawk2** [comment]
Somewhat redundant with #100 - a popular problem it seems!

**Comment by mohawk2** [comment]
Thank you! This has been addressed in a more minimal fashion in #100 now.

**Pull request closed without merging**
